[package]
name = "warp-reverse-proxy"
version = "0.1.0"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2.4"
http = "0.2.1"
hyper = "0.13.7"
reqwest = "0.10.7"

[dev-dependencies]
bytes = "0.5.6"
tokio = { version = "0.2.22", features = ["macros"] }